### ISSUE TITLE
Small typo at destroy project helper

### ISSUE THREAD

**Issue by sangdth** [Easypanel-Community/easypanel#11]
https://github.com/Easypanel-Community/easypanel/blob/d82f2a8107d952b6ea90ac2d8f625ee69c1c7bb6/src/service/projects.ts#L31C21-L31C21

It should be `destroy`, currently it's `destory` 😸

**Comment by productdevbook** [comment]
![image](https://github.com/Easypanel-Community/easypanel/assets/38668796/6ee19e23-a062-4a53-bce9-da9ff70a4331)

but the APIs are like this

**Comment by sangdth** [comment]
Yes, the endpoint is correct, but I still have to call the method `app.projects.destory()`.
