### ISSUE TITLE
How to use with Two Factor Authentication

### ISSUE THREAD

**Issue by sangdth** [Easypanel-Community/easypanel#3]
My account has Two Factor Authentication, is there other way to login?

**Comment by Supernova3339** [comment]
> My account has Two Factor Authentication, is there other way to login?

You can use an API key that comes with v1.27.1

**Comment by productdevbook** [comment]
we are switching to the token feature and the auth feature will be removed in the new version. 

- [ ] https://github.com/Easypanel-Community/easypanel/pull/4

**Comment by productdevbook** [comment]
[v.0.1.0](https://github.com/Easypanel-Community/easypanel/releases/tag/v0.1.0)

**Comment by sangdth** [comment]
Thanks! This is fast <3
